export const ERROR_TYPES = {
    CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
    PRODUCT_FOR_SALE_NOT_FOUND: "PRODUCT_FOR_SALE_NOT_FOUND",
    INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
    SELLING_PRICE_NOT_FOUND: "SELLING_PRICE_NOT_FOUND",
}